import { useEffect, useMemo } from 'react';
import { BookOpen, Box, ChevronDown, ChevronLeft, ChevronRight, Copy, Layers3, Leaf, Maximize2, MoreHorizontal, MousePointer2, Pause, Play, Plus, Redo2, Save, Scissors, Settings2, Undo2 } from 'lucide-react';
import { useStudio } from './store';
import { compileProject, evaluateSpread } from './engine/geometry';
import { PRESETS } from './presets';
import Viewer from './components/Viewer';

export default function App() {
  const s = useStudio(), spread = s.project.spreads.find(p => p.id === s.activeSpreadId)!;
  const compiled = useMemo(() => compileProject(s.project, s.activeSpreadId), [s.project, s.activeSpreadId]);
  const pose = useMemo(() => evaluateSpread(compiled, s.angle, s.drivers), [compiled, s.angle, s.drivers]);
  const selected = pose.parts.find(p => p.id === s.selectedId), mechanism = spread.mechanisms.find(m => selected?.mechanismId === m.id);
  useEffect(() => { if (!s.playing) return; let frame = 0, previous = performance.now(), direction = s.angle >= 179 ? -1 : 1; const step = (now: number) => { const state = useStudio.getState(); let angle = state.angle + direction * Math.min(now - previous, 50) * 0.025; previous = now; if (angle >= 180) { angle = 180; direction = -1; } if (angle <= 0) { angle = 0; direction = 1; } state.set({ angle }); frame = requestAnimationFrame(step); }; frame = requestAnimationFrame(step); return () => cancelAnimationFrame(frame); }, [s.playing]);
  const update = (key: string, value: number) => mechanism && s.edit('Mechanism updated', p => { const m = p.spreads.find(p => p.id === spread.id)!.mechanisms.find(m => m.id === mechanism.id)!; Object.assign(m, { [key]: value }); });
  return <div className={`studio ${s.reader ? 'reader-mode' : ''}`}>
    <header className="app-header"><a className="brand" href="#" onClick={e => e.preventDefault()}><div className="brand-mark"><BookOpen size={21} /></div><strong>fold<span>studio</span></strong></a><div className="header-separator" /><div className="project-title">{s.project.name}<ChevronDown size={14} /><span className="local-badge">LOCAL PROJECT</span></div><div className="header-right"><span className="save-state"><span className="status-dot" />Device-local workspace</span><button className={`button subtle ${s.reader ? 'active' : ''}`} onClick={() => s.set({ reader: !s.reader })}><BookOpen size={16} />{s.reader ? 'Back to editor' : 'Read book'}</button></div></header>
    <div className="workspace">
      <aside className="left-panel"><div className="panel-label">YOUR BOOK <button className="icon-button" title="Add spread" aria-label="Add spread" onClick={s.addSpread}><Plus size={16} /></button></div><div className="spread-list">{s.project.spreads.map((page, i) => <button key={page.id} className={`spread-card ${page.id === spread.id ? 'selected' : ''}`} onClick={() => s.selectSpread(page.id)}><div className="spread-thumbnail" style={{ '--paper-accent': page.color } as React.CSSProperties}><span /><span /><i /></div><div><small>SPREAD {String(i + 1).padStart(2, '0')}</small><strong>{page.name}</strong><span>{page.mechanisms.length} mechanisms</span></div></button>)}</div><div className="spread-management"><button onClick={s.duplicateSpread} title="Duplicate spread" aria-label="Duplicate spread"><Copy size={14} /></button><button onClick={() => s.moveSpread(-1)} title="Move spread earlier" aria-label="Move spread earlier"><ChevronLeft size={16} /></button><button onClick={() => s.moveSpread(1)} title="Move spread later" aria-label="Move spread later"><ChevronRight size={16} /></button></div><div className="library-heading"><div><span className="eyebrow">PAPER ENGINEERING</span><h2>Mechanisms</h2></div><Scissors size={18} /></div><div className="mechanism-library">{PRESETS.map((preset, i) => <button key={preset.kind} onClick={() => s.addPreset(preset.kind)} className="mechanism-card"><div className={`mechanism-icon icon-${i}`}>{i === 2 ? <Leaf size={20} /> : i === 5 ? <Maximize2 size={20} /> : <Layers3 size={20} />}</div><div><strong>{preset.name}</strong><small>{preset.tag}</small></div><Plus size={15} /></button>)}</div><div className="library-tip"><Box size={16} /><p>Start with a fold.<br />Build something extraordinary.</p></div></aside>
      <main className="main-panel"><div className="document-heading"><div><div className="eyebrow">SPREAD {String(s.project.spreads.indexOf(spread) + 1).padStart(2, '0')} <span>/ {String(s.project.spreads.length).padStart(2, '0')}</span></div><h1>{spread.name}</h1><p>{spread.subtitle}</p></div><button className="icon-button" onClick={() => s.set({ selectedId: null })} title="Spread settings" aria-label="Spread settings"><Settings2 size={19} /></button></div><div className="canvas-toolbar"><div className="segmented"><button className="active"><Box size={15} />3D model</button></div><span className="dimension-label">{s.project.pageWidth * 2} × {s.project.pageHeight} mm</span><div className="toolbar-right"><button className="icon-button" onClick={s.undo} disabled={!s.past.length} title="Undo" aria-label="Undo"><Undo2 size={17} /></button><button className="icon-button" onClick={s.redo} disabled={!s.future.length} title="Redo" aria-label="Redo"><Redo2 size={17} /></button></div></div><div className="canvas-area"><Viewer compiled={compiled} /></div><div className="playback-bar"><button className={`play-button ${s.playing ? 'playing' : ''}`} onClick={() => s.set({ playing: !s.playing })} aria-label={s.playing ? 'Pause folding' : 'Play folding'}>{s.playing ? <Pause size={17} fill="currentColor" /> : <Play size={17} fill="currentColor" />}</button><div className="opening-label"><strong>Book opening</strong><span>{s.playing ? 'Playing fold sequence' : 'Scrub to explore the mechanism'}</span></div><span className="angle-end">0°</span><input aria-label="Book opening angle" className="angle-slider" type="range" min="0" max="180" step="0.1" value={s.angle} onChange={e => s.set({ angle: +e.target.value, playing: false })} style={{ '--progress': `${s.angle / 1.8}%` } as React.CSSProperties} /><span className="angle-end">180°</span><output className="angle-value">{Math.round(s.angle)}<span>°</span></output></div><div className="workspace-footer"><span><span className="status-dot" />{pose.parts.length - 2} paper parts <span className="muted">·</span> {spread.mechanisms.length} mechanisms</span><span>Rigid paper · Geometry preview</span></div></main>
      <aside className="right-panel"><div className="panel-label">{selected ? 'PART PROPERTIES' : 'SPREAD PROPERTIES'}<Settings2 size={15} /></div><div className="inspector-intro"><span className="inspector-symbol">{selected ? <Layers3 size={24} /> : <BookOpen size={24} />}</span><h2>{selected?.name ?? spread.name}</h2><p>{mechanism ? PRESETS.find(p => p.kind === mechanism.kind)?.description : 'Select a paper part to shape its geometry.'}</p></div><div className="inspector-section"><h3>{mechanism ? 'Dimensions' : 'Page setup'}</h3>{mechanism ? <>{[['width', 'Width'], ['reach', 'Closed reach'], ['offset', 'Along hinge']].map(([key, label]) => <label className="property-row" key={key}><span>{label}</span><div className="number-field"><input type="number" aria-label={label} value={mechanism[key as 'width' | 'reach' | 'offset']} onChange={e => update(key, +e.target.value)} /><span>mm</span></div></label>)}<label className="property-row"><span>Paper color</span><input type="color" aria-label="Paper color" value={mechanism.color} onChange={e => s.edit('Paper color updated', p => { p.spreads.find(p => p.id === spread.id)!.mechanisms.find(m => m.id === mechanism.id)!.color = e.target.value; })} /></label></> : <>{[['pageWidth', 'Page width'], ['pageHeight', 'Page height']].map(([key, label]) => <label className="property-row" key={key}><span>{label}</span><div className="number-field"><input aria-label={label} type="number" min="20" value={s.project[key as 'pageWidth' | 'pageHeight']} onChange={e => s.edit('Page size updated', p => Object.assign(p, { [key]: Math.max(20, +e.target.value) }))} /><span>mm</span></div></label>)}<div className="small-note">A5 portrait · Dimensions apply to every spread.</div></>}</div><div className="inspector-section"><h3>Structure <span>{spread.mechanisms.length}</span></h3><div className="structure-tree"><button onClick={() => s.set({ selectedId: null })}><BookOpen size={15} />Book spine</button>{spread.mechanisms.map(m => <button key={m.id} className={mechanism?.id === m.id ? 'selected' : ''} style={{ marginLeft: m.host === 'spine' || m.host.startsWith('page-') ? 10 : 22 }} onClick={() => s.set({ selectedId: `${m.id}:${m.kind === 'slider' ? 'strip' : 'left'}` })}><span className="tree-line" /><span className="color-chip" style={{ background: m.color }} />{m.name}</button>)}</div></div><div className="inspector-bottom"><MousePointer2 size={16} /><span>Click a part in the viewer to inspect it.</span></div></aside>
    </div><footer className="app-status"><span>FOLD STUDIO <span className="version">/ 0.1</span></span><span>{pose.diagnostics[0]?.message ?? s.notice ?? 'Ready'}</span><span><Save size={12} />LOCAL WORKSPACE</span></footer>
  </div>;
}
